# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jonas' Blog
email: jonasbush@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Development blog for Jonas Bush, documenting the struggles of a 13-year .Net developer in the OSS world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://JXPrime.github.io" # the base hostname & protocol for your site
twitter_username: JXPrime
github_username:  JXPrime
timezone: America/Phoenix

# Build settings
markdown: kramdown
